### PR TITLE
check slack webhook result; move run status to property

### PR DESCRIPTION
**Pull request by glensc**
this is fix for #29

this is my old changes, don't recall why i did it this way or another way, or check will it work with newer chef too, but it may help @kjwierenga.

merge if it works for you, i can confirm it works with chef-11.16.4

### CODE REVIEW

**Comment by shortdudey123** [comment]
@glensc can you fix the Rubocop errors please? :)

**Comment by glensc** [comment]
@shortdudey123 those errors are silly. but ok

**Comment by BetaFold3** [comment]
Thank you. Can we expect this will be released soon?

**Comment by martinb3** [comment]
@tuannh99 it's been released as v0.8.0 👍

**Comment by BetaFold3** [comment]
Thank you.
That's fast.
Unfortunately, I still met this error:

> Running handlers:
> [2016-09-16T10:25:03+00:00] WARN: Failed to send message to Slack: undefined local variable or method `run_context' for #SlackHandlerUtil:0x00000010c3cc28
> - Chef::Handler::Slack
>   Running handlers complete

Edit: I'm wondering whether slack_handler required a minimum version of chef_handler?
I want to note that I had been using slack_handler properly, until 1 month ago.

**Comment by martinb3** [comment]
@tuannh99 can you open a separate issue with exactly what versions of chef you're using, as well as how you're calling this cookbook?

**Comment by BetaFold3** [comment]
@martinb3 Okie, I will create another issue.
